name: Sync to Hugging Face Spaces
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Force push to HF Spaces. 
          # Replace '<HF_USERNAME>/<HF_SPACE_NAME>' with your actual Hugging Face account username and Space name.
          git push --force https://<HF_USERNAME>:$HF_TOKEN@huggingface.co/spaces/<HF_USERNAME>/<HF_SPACE_NAME>

