name: Sync to Hugging Face Spaces
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git checkout --orphan hf-sync
          git rm -rf .
          git checkout $GITHUB_SHA -- .
          find . -name "*.docx" -delete
          git add .
          git commit -m "Sync to HF Space"
          git push --force https://voldigo:$HF_TOKEN@huggingface.co/spaces/voldigo/redrob-ai-candidate-ranker hf-sync:main
